import DErrorBoundary from "@/components/DErrorBoundary";
import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";

import "./globals.css";
import { ReactQueryProvider } from "./providers/ReactQueryProvider";

const space_grostek = Space_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${space_grostek.className} antialiased`}>
        <DErrorBoundary>
          <ReactQueryProvider>{children}</ReactQueryProvider>
        </DErrorBoundary>
      </body>
    </html>
  );
}
