name: Next.js CI/CD Pipeline

on:
  push:
    branches: [ main, canary ]
  pull_request:
    branches: [ main, canary ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '23.4.0'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Lint check
      run: npm run lint
    
    - name: Type check
      run: npm run type-check 

    # - name: Run tests
    # run: npm test
    
    - name: Build
      run: npm run build
    
    - name: Cache build output
      uses: actions/cache@v3
      with:
        path: |
          .next
          node_modules
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}

  branch-protection:
    needs: [build-and-test]
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Block merging if checks fail
      uses: softprops/action-gh-release@v1
      if: failure()
      with:
        draft: false
        prerelease: false